### ISSUE TITLE
Hacktoberfest Contributions

### ISSUE THREAD

**Issue by kaiiyer** [kaiiyer/anti-corruption#1]
UI improvements and bug fixes

**Comment by bonniesimon** [comment]
What UI improvements are needed?

**Comment by kaiiyer** [comment]
@bonniesimon
 It's hacktober season so no specific UI components
Anything you find suitable bro

**Comment by lukes-code** [comment]
Hi, I've created a small PR. Thanks

**Comment by kaiiyer** [comment]
> Hi, I've created a small PR. Thanks

Thanks for the contribution. I've merged your pull

**Comment by kaiiyer** [comment]
Thanks for the contributions during Hacktoberfest !!!
